### ISSUE TITLE
复现

### ISSUE THREAD

**Issue by lima5264** [AMPLE001/AMPLE#5]
有人复现出来代码吗？或者正在复现的，望交流。

**Comment by zfc520621** [comment]
正在复现

**Comment by lima5264** [comment]
> 正在复现

v 19862708169 交流

**Comment by forDuan** [comment]
> 有人复现出来代码吗？或者正在复现的，望交流。

你好，请问你复现出来了吗，可以交流下吗

**Comment by RetrievalBackdoorDefense** [comment]
GGNNSum 没找到啊

**Comment by mcf20** [comment]
> > 正在复现
> 
> v 19862708169 交流

 搜不到啊
